name: "itscheems/pr-checker"
description: "Validate pull request rules (title pattern, labels, etc.)"
author: "itscheems"
branding:
  icon: "check-circle"
  color: "green"

runs:
  using: docker
  image: Dockerfile

inputs:
  config:
    description: "Path to PR checker config file"
    required: false
    default: "pr-checker.yml"
